In [25]:

import pandas as pd
import numpy as np

print("STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("Project started successfully!")

STUDENT PERFORMANCE ANALYTICS SYSTEM
Project started successfully!

In [26]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

Pandas helps us read and analyze student data.
NumPy helps us calculate total and average marks.

In [29]:
df = pd.read_csv("/content/students.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [30]:
df.head()

,Student_ID,Name,Department,Python,Mathematics,Database,Communication,Attendance_Percent
0,S001,Aarav,ISE,85,78,92,88,91
1,S002,Ananya,CSE,92,89,95,94,96
2,S003,Rahul,ECE,65,72,68,70,82
3,S004,Sneha,ISE,74,81,77,79,90
4,S005,Vikram,CSE,58,61,55,64,75

This displays the first five student records.

In [31]:
print("Dataset shape:", df.shape)

print("\nColumn names:")
print(df.columns)

print("\nDataset information:")
df.info()

Dataset shape: (30, 8)

Column names:
Index(['Student_ID', 'Name', 'Department', 'Python', 'Mathematics', 'Database',
       'Communication', 'Attendance_Percent'],
      dtype='object')

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          30 non-null     object
 1   Name                30 non-null     object
 2   Department          30 non-null     object
 3   Python              30 non-null     int64
 4   Mathematics         30 non-null     int64
 5   Database            30 non-null     int64
 6   Communication       30 non-null     int64
 7   Attendance_Percent  30 non-null     int64
dtypes: int64(5), object(3)
memory usage: 2.0+ KB

This helps you check the number of students, column names, and data types.

In [32]:

# Select the subjects
subjects = ["Python", "Mathematics", "Database", "Communication"]

# Calculate total marks
df["Total_Marks"] = np.sum(df[subjects].to_numpy(), axis=1)

# Calculate average marks
df["Average_Marks"] = np.mean(df[subjects].to_numpy(), axis=1)

# Display the results
display(df[["Name", *subjects, "Total_Marks", "Average_Marks"]])

,Name,Python,Mathematics,Database,Communication,Total_Marks,Average_Marks
0,Aarav,85,78,92,88,343,85.75
1,Ananya,92,89,95,94,370,92.50
2,Rahul,65,72,68,70,275,68.75
3,Sneha,74,81,77,79,311,77.75
4,Vikram,58,61,55,64,238,59.50
5,Priya,96,94,98,93,381,95.25
6,Kiran,43,52,48,56,199,49.75
7,Divya,81,86,84,80,331,82.75
8,Arjun,69,63,71,66,269,67.25
9,Meera,88,91,86,90,355,88.75
10,Rohan,35,44,39,48,166,41.50
11,Kavya,77,73,82,79,311,77.75
12,Ishaan,90,84,88,92,354,88.50
13,Pooja,62,68,64,71,265,66.25
14,Aditya,54,57,60,52,223,55.75
15,Nisha,83,79,85,81,328,82.00
16,Manoj,71,66,74,69,280,70.00
17,Sanjana,98,96,97,99,390,97.50
18,Deepak,47,59,51,55,212,53.00
19,Aditi,76,82,79,84,321,80.25
20,Neha,87,85,90,86,348,87.00
21,Varun,67,74,70,73,284,71.00
22,Riya,93,90,94,91,368,92.00
23,Suraj,52,48,57,61,218,54.50
24,Tanya,79,83,81,85,328,82.00
25,Harish,41,46,44,50,181,45.25
26,Ira,86,88,82,90,346,86.50
27,Akash,73,70,76,72,291,72.75
28,Maya,95,93,96,97,381,95.25
29,Nitin,60,65,62,67,254,63.50

- subjects stores the names of the four subject columns.
- to_numpy() converts the subject marks into a NumPy array.
- np.sum(..., axis=1) calculates the total marks for each student.
- np.mean(..., axis=1) calculates each student's average marks.
- display() shows the results in a table.
Since there are four subjects, the maximum total is 400 if each subject is marked out of 100.

In [33]:

print("Total students:", len(df))
print("Class average:", round(df["Average_Marks"].mean(), 2))
print("Highest average:", round(df["Average_Marks"].max(), 2))
print("Lowest average:", round(df["Average_Marks"].min(), 2))

Total students: 30
Class average: 74.34
Highest average: 97.5
Lowest average: 41.5

These calculations help summarize the class performance.

In [34]:

# Function to calculate student grades
def calculate_grade(average):
    if average >= 90:
        return "A"
    elif average >= 80:
        return "B"
    elif average >= 70:
        return "C"
    elif average >= 60:
        return "D"
    elif average >= 50:
        return "E"
    else:
        return "F"


# Apply the function to every student
df["Grade"] = df["Average_Marks"].apply(calculate_grade)

# Display student grades
display(df[["Name", "Average_Marks", "Grade"]])

       Name  Average_Marks Grade
0     Aarav          85.75     B
1    Ananya          92.50     A
2     Rahul          68.75     D
3     Sneha          77.75     C
4    Vikram          59.50     E
5     Priya          95.25     A
6     Kiran          49.75     F
7     Divya          82.75     B
8     Arjun          67.25     D
9     Meera          88.75     B
10    Rohan          41.50     F
11    Kavya          77.75     C
12   Ishaan          88.50     B
13    Pooja          66.25     D
14   Aditya          55.75     E
15    Nisha          82.00     B
16    Manoj          70.00     C
17  Sanjana          97.50     A
18   Deepak          53.00     E
19    Aditi          80.25     B
20     Neha          87.00     B
21    Varun          71.00     C
22     Riya          92.00     A
23    Suraj          54.50     E
24    Tanya          82.00     B
25   Harish          45.25     F
26      Ira          86.50     B
27    Akash          72.75     C
28     Maya          95.25     A
29    Nitin          63.50     D

- def creates a function named calculate_grade.
- if and elif check the student's average marks.
- return gives back the appropriate grade.
- .apply(calculate_grade) applies the function to every student's average.
- df["Grade"] stores the grades in a new column.
These grade boundaries are the rules we're choosing for this project.

In [35]:

def calculate_result(row):
    if row[subjects].min() >= 35 and row["Average_Marks"] >= 40:
        return "PASS"
    else:
        return "FAIL"


df["Result"] = df.apply(calculate_result, axis=1)

display(df[["Name", "Average_Marks", "Grade", "Result"]])

       Name  Average_Marks Grade Result
0     Aarav          85.75     B   PASS
1    Ananya          92.50     A   PASS
2     Rahul          68.75     D   PASS
3     Sneha          77.75     C   PASS
4    Vikram          59.50     E   PASS
5     Priya          95.25     A   PASS
6     Kiran          49.75     F   PASS
7     Divya          82.75     B   PASS
8     Arjun          67.25     D   PASS
9     Meera          88.75     B   PASS
10    Rohan          41.50     F   PASS
11    Kavya          77.75     C   PASS
12   Ishaan          88.50     B   PASS
13    Pooja          66.25     D   PASS
14   Aditya          55.75     E   PASS
15    Nisha          82.00     B   PASS
16    Manoj          70.00     C   PASS
17  Sanjana          97.50     A   PASS
18   Deepak          53.00     E   PASS
19    Aditi          80.25     B   PASS
20     Neha          87.00     B   PASS
21    Varun          71.00     C   PASS
22     Riya          92.00     A   PASS
23    Suraj          54.50     E   PASS
24    Tanya          82.00     B   PASS
25   Harish          45.25     F   PASS
26      Ira          86.50     B   PASS
27    Akash          72.75     C   PASS
28     Maya          95.25     A   PASS
29    Nitin          63.50     D   PASS

Pass rule: A student must score at least 35 in every subject and have an average of at least 40.

In [36]:

# Class performance statistics

total_students = len(df)

class_average = df["Average_Marks"].mean()

highest_average = df["Average_Marks"].max()

lowest_average = df["Average_Marks"].min()

pass_count = (df["Result"] == "PASS").sum()

fail_count = (df["Result"] == "FAIL").sum()

pass_percentage = (pass_count / total_students) * 100

average_attendance = df["Attendance_Percent"].mean()

print("===== CLASS PERFORMANCE REPORT =====")
print("Total Students:", total_students)
print("Class Average:", round(class_average, 2))
print("Highest Average:", round(highest_average, 2))
print("Lowest Average:", round(lowest_average, 2))
print("Students Passed:", pass_count)
print("Students Failed:", fail_count)
print("Pass Percentage:", round(pass_percentage, 2), "%")
print("Average Attendance:", round(average_attendance, 2), "%")

===== CLASS PERFORMANCE REPORT =====
Total Students: 30
Class Average: 74.34
Highest Average: 97.5
Lowest Average: 41.5
Students Passed: 30
Students Failed: 0
Pass Percentage: 100.0 %
Average Attendance: 84.67 %

len() counts students.



.mean() calculates the average.



.max() and .min() find the highest and lowest values.



.sum() counts how many students passed or failed.



Pass percentage shows the proportion of students who passed.

In [37]:

print("===== SUBJECT-WISE PERFORMANCE =====")

for subject in subjects:
    print("\nSubject:", subject)
    print("Average Marks:", round(df[subject].mean(), 2))
    print("Highest Marks:", df[subject].max())
    print("Lowest Marks:", df[subject].min())

subject_averages = df[subjects].mean()

print("\nBest Performing Subject:", subject_averages.idxmax())
print("Lowest Performing Subject:", subject_averages.idxmin())

===== SUBJECT-WISE PERFORMANCE =====

Subject: Python
Average Marks: 72.57
Highest Marks: 98
Lowest Marks: 35

Subject: Mathematics
Average Marks: 73.9
Highest Marks: 96
Lowest Marks: 44

Subject: Database
Average Marks: 74.83
Highest Marks: 98
Lowest Marks: 39

Subject: Communication
Average Marks: 76.07
Highest Marks: 99
Lowest Marks: 48

Best Performing Subject: Communication
Lowest Performing Subject: Python

This uses a for loop to analyze all four subjects without repeating the same code manually

In [38]:

# Find the top 3 students based on average marks

top_students = df.nlargest(3, "Average_Marks")

print("===== TOP 3 PERFORMING STUDENTS =====")

display(
    top_students[
        ["Student_ID", "Name", "Department",
         "Average_Marks", "Grade"]
    ]
)

===== TOP 3 PERFORMING STUDENTS =====

   Student_ID     Name Department  Average_Marks Grade
17       S018  Sanjana        CSE          97.50     A
5        S006    Priya        ISE          95.25     A
28       S029     Maya        CSE          95.25     A

nlargest(3, "Average_Marks") selects the three students with the highest average marks.

In [39]:

# Find students who scored above 80 in Python

high_python_scores = df[df["Python"] > 80]

print("===== STUDENTS SCORING ABOVE 80 IN PYTHON =====")

display(
    high_python_scores[
        ["Name", "Python", "Average_Marks", "Grade"]
    ]
)

===== STUDENTS SCORING ABOVE 80 IN PYTHON =====

       Name  Python  Average_Marks Grade
0     Aarav      85          85.75     B
1    Ananya      92          92.50     A
5     Priya      96          95.25     A
7     Divya      81          82.75     B
9     Meera      88          88.75     B
12   Ishaan      90          88.50     B
15    Nisha      83          82.00     B
17  Sanjana      98          97.50     A
20     Neha      87          87.00     B
22     Riya      93          92.00     A
26      Ira      86          86.50     B
28     Maya      95          95.25     A

This uses a Pandas condition to filter students whose Python marks are greater than 80.

In [40]:

# Save the analyzed dataset

df.to_csv("student_performance_results.csv", index=False)

print("Project results saved successfully!")

Project results saved successfully!

In [42]:

df.to_csv("/content/student_performance_results.csv", index=False)

print("Results saved successfully!")

Results saved successfully!

Save the final results

In [43]:

import os

print(os.path.exists("/content/student_performance_results.csv"))
print(os.listdir("/content"))

True
['.config', 'students.csv', '.ipynb_checkpoints', 'student_performance_results.csv', 'sample_data']

In [44]:

from google.colab import files

files.download("/content/student_performance_results.csv")

To download the results

# Student Performance Analytics System

## 1. Project Objective

The objective of this project is to analyze student academic performance using Python, NumPy, and Pandas. The system calculates total marks, average marks, grades, and pass/fail results. It also analyzes subject-wise performance and identifies the top three students.

## 2. Technologies Used

- **Python:** Used for programming logic, functions, loops, and conditional statements.
- **NumPy:** Used for calculating total and average marks.
- **Pandas:** Used for loading, processing, filtering, and analyzing student data.
- **Google Colab:** Used to write and execute Python code online.

## 3. Dataset Description

The dataset contains student information, subject marks, and attendance percentages. It is used to analyze academic performance and generate student results.

## 4. Project Features

1. Load and display the student dataset.
2. Calculate total marks for each student.
3. Calculate average marks for each student.
4. Assign grades based on average marks.
5. Classify students as PASS or FAIL.
6. Calculate overall class performance statistics.
7. Analyze subject-wise average, highest, and lowest marks.
8. Identify the top three performing students.
9. Filter students who scored above 80 in Python.
10. Save the analyzed results as a CSV file.

## 5. Expected Outcome

The system generates a structured analysis of student performance, helps identify high-performing students and weaker subjects, and exports the results to a CSV file for further use.